<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
    <line>
      <![CDATA[这是我自己的log输出]]>
    </line>
  </reporter-output>
  <suite name="Default Suite" duration-ms="270" started-at="2018-10-27T10:04:50Z" finished-at="2018-10-27T10:04:50Z">
    <groups>
    </groups>
    <test name="Jiekou" duration-ms="270" started-at="2018-10-27T10:04:50Z" finished-at="2018-10-27T10:04:50Z">
      <class name="demo.TESTS">
        <test-method status="FAIL" signature="log()[pri:0, instance:demo.TESTS@2ac1fdc4]" name="log" duration-ms="28" started-at="2018-10-27T18:04:50Z" finished-at="2018-10-27T18:04:50Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[自己跑出的异常]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: 自己跑出的异常
	at demo.TESTS.log(TESTS.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
            <line>
              <![CDATA[这是我自己的log输出]]>
            </line>
          </reporter-output>
        </test-method> <!-- log -->
        <test-method status="PASS" signature="t1()[pri:0, instance:demo.TESTS@2ac1fdc4]" name="t1" duration-ms="9" started-at="2018-10-27T18:04:50Z" finished-at="2018-10-27T18:04:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t1 -->
        <test-method status="PASS" signature="t2()[pri:0, instance:demo.TESTS@2ac1fdc4]" name="t2" duration-ms="1" started-at="2018-10-27T18:04:50Z" finished-at="2018-10-27T18:04:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t2 -->
      </class> <!-- demo.TESTS -->
    </test> <!-- Jiekou -->
  </suite> <!-- Default Suite -->
</testng-results>
