<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="XULE" ignored="0" name="Jiekou" tests="3" failures="1" timestamp="27 十月 2018 10:04:51 GMT" time="0.27" errors="0">
  <testcase name="log" time="0.028" classname="demo.TESTS">
    <failure type="java.lang.RuntimeException" message="自己跑出的异常">
      <![CDATA[java.lang.RuntimeException: 自己跑出的异常
	at demo.TESTS.log(TESTS.java:22)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- log -->
  <testcase name="t1" time="0.009" classname="demo.TESTS"/>
  <testcase name="t2" time="0.001" classname="demo.TESTS"/>
</testsuite> <!-- Jiekou -->
